name: Deploy Image to Google Cloud Run

on: [push]

env:
  ARTIFACT_REGISTRY: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
  REGION: ${{ secrets.REGION }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}


jobs:

  deploy-cloud-run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: Deploy Image to Google Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: cloud_run_service_name
          region: ${{ env.REGION }}
          image: image_url

      - name: Get Cloud Run Service URL
        run: |
          echo ${{ steps.deploy.outputs.url }}
