name: Push Docker Image to Google Artifact Registry

on: [push]

env:
  ARTIFACT_REGISTRY: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
  REGION: ${{ secrets.REGION }}
  SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: project_id
  API_ID: api_id
  API_GATEWAY_ID: api_gateway_id
  API_CONFIG_NAME: config_name


jobs:

  deploy-api-gateway:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: Create API Config
        run: |
          gcloud api-gateway api-configs create ${{ env.API_CONFIG_NAME }} \ 
          --api=${{ env.API_ID }} \
          --openapi-spec=api_config.yaml \
          --project=${{ env.PROJECT_ID }} \
          --backend-auth-service-account=${{ env.SERVICE_ACCOUNT_NAME }}

      - name: Deploy API Gateway
        id: deploy-api-gateway
        run: |
          gcloud api-gateway gateways create ${{ env.API_GATEWAY_ID }} \
          --api=${{ env.API_ID }} \
          --api-config=${{ env.API_CONFIG_NAME }} \
          --location=${{ env.REGION }}
          
          echo "::set-output name=MANAGED_SERVICE_URL::$(gcloud api-gateway apis describe ${{ env.API_ID }} | sed -n 's/.*managedService: //p')"
          echo "::set-output name=GATEWAY_URL::$(gcloud api-gateway gateways describe ${{ env.API_GATEWAY_ID }} --location=${{ inputs.region }} | sed -n 's/.*defaultHostname: /https:\/\//p')"

      - name: Enable API Gateway
        run: |
          gcloud services enable ${{ steps.deploy-api-gateway.outputs.MANAGED_SERVICE_URL }}

      - name: Get API Gateway URL
        run: |
          echo ${{ steps.deploy-api-gateway.outputs.GATEWAY_URL }}
